module.exports = {
    pics: getPics()
};

function getPics() {
    return [
        //{id: 1, firstName: 'John', lastName: 'Papa', age: 25, location: 'Florida'},
        //{id: 2, firstName: 'Ward', lastName: 'Bell', age: 31, location: 'California'},
        //{id: 3, firstName: 'Colleen', lastName: 'Jones', age: 21, location: 'New York'},
        //{id: 4, firstName: 'Madelyn', lastName: 'Green', age: 18, location: 'North Dakota'},
        //{id: 5, firstName: 'Ella', lastName: 'Jobs', age: 18, location: 'South Dakota'},
        //{id: 6, firstName: 'Landon', lastName: 'Gates', age: 11, location: 'South Carolina'},
        //{id: 7, firstName: 'Haley', lastName: 'Guthrie', age: 35, location: 'Wyoming'},
        //{id: 8, firstName: 'Aaron', lastName: 'Jinglehiemer', age: 22, location: 'Utah'}
        {id: 1, title: 'First Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/nightlife',
            url: 'https://lorempixel.com/600/800/nightlife'},
        {id: 2, title: 'Second Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/cats',
            url: 'https://lorempixel.com/600/800/cats'},
        {id: 3, title: 'Third Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/food',
            url: 'https://lorempixel.com/600/800/food'},
        {id: 4, title: 'First Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/cats',
            url: 'https://lorempixel.com/600/800/cats'},
        {id: 5, title: 'Second Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/nightlife',
            url: 'https://lorempixel.com/600/800/nightlife'},
        {id: 6, title: 'Third Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/food',
            url: 'https://lorempixel.com/600/800/food'},
        {id: 7, title: 'First Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/nightlife',
            url: 'https://lorempixel.com/600/800/nightlife'},
        {id: 8, title: 'Second Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/food',
            url: 'https://lorempixel.com/600/800/food'},
        {id: 9, title: 'Third Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/cats',
            url: 'https://lorempixel.com/600/800/cats'},
        {id: 10, title: 'First Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/nightlife',
            url: 'https://lorempixel.com/600/800/nightlife'},
        {id: 11, title: 'Second Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/cats',
            url: 'https://lorempixel.com/600/800/cats'},
        {id: 12, title: 'Third Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/food',
            url: 'https://lorempixel.com/600/800/food'},
        {id: 13, title: 'First Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/nightlife',
            url: 'https://lorempixel.com/600/800/nightlife'},
        {id: 14, title: 'Second Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/cats',
            url: 'https://lorempixel.com/600/800/cats'},
        {id: 15, title: 'Third Pic!', caption: 'First pic',
            thumbUrl: 'https://lorempixel.com/350/450/food',
            url: 'https://lorempixel.com/600/800/food'}
    ];
}
